from .department import Department
from .faculty import Faculty
from .group import Group
from .result_student import ResultStudent
from .subject import Subject
from .teacher import Teacher
from .student import Student
from .user import User
from .question import Question