"""Change teacher table

Revision ID: 0219e83d2eb9
Revises: c63395449873
Create Date: 2025-02-07 16:12:22.088818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0219e83d2eb9'
down_revision: Union[str, None] = 'c63395449873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teachers', 'jshir',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'jshir',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    op.alter_column('teachers', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teachers', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
