"""Change subject

Revision ID: 0556068548be
Revises: 6e5bcf74c566
Create Date: 2025-03-08 11:11:50.543451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0556068548be'
down_revision: Union[str, None] = '6e5bcf74c566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subjects_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.drop_constraint('subjects_group_id_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    op.drop_column('subjects', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('subjects_group_id_fkey', 'subjects', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('subjects_teacher_id_fkey', 'subjects', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
