"""add some passport

Revision ID: 3e7cbb6d357b
Revises: 22acda31e057
Create Date: 2025-03-01 13:46:12.499226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7cbb6d357b'
down_revision: Union[str, None] = '22acda31e057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('passport', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['passport'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'passport')
    # ### end Alembic commands ###
