"""Add image option

Revision ID: 88abe6be5b38
Revises: 5c7f9a6c64cd
Create Date: 2025-02-19 15:06:47.958398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88abe6be5b38'
down_revision: Union[str, None] = '5c7f9a6c64cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('option_A_image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_b_image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_c_image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_d_image', sa.String(), nullable=True))
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'A',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'B',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'C',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'D',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'D',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'C',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'B',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'A',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('questions', 'option_d_image')
    op.drop_column('questions', 'option_c_image')
    op.drop_column('questions', 'option_b_image')
    op.drop_column('questions', 'option_A_image')
    # ### end Alembic commands ###
