"""Add image in model

Revision ID: e30fea7be82b
Revises: 88abe6be5b38
Create Date: 2025-02-19 15:23:07.962271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30fea7be82b'
down_revision: Union[str, None] = '88abe6be5b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_a', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_a_image', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_b', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_c', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('option_d', sa.String(), nullable=True))
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.drop_column('questions', 'A')
    op.drop_column('questions', 'C')
    op.drop_column('questions', 'D')
    op.drop_column('questions', 'option_A_image')
    op.drop_column('questions', 'imgae')
    op.drop_column('questions', 'B')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('B', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('imgae', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('option_A_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('D', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('C', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('A', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.alter_column('questions', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('questions', 'option_d')
    op.drop_column('questions', 'option_c')
    op.drop_column('questions', 'option_b')
    op.drop_column('questions', 'option_a_image')
    op.drop_column('questions', 'option_a')
    op.drop_column('questions', 'image')
    # ### end Alembic commands ###
